# Generated by Django 4.2.1 on 2023-06-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpticaSolyGafas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
            ],
        ),
    ]
