# Generated by Django 4.2.1 on 2023-06-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('politica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.politica')),
            ],
        ),
        migrations.CreateModel(
            name='Tactica',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.estrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tactica_Regla',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.regla')),
                ('tactica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.tactica')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEsperado',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('optica', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.objetivos')),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('resultado_esperado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.resultadoesperado')),
                ('vision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.vision')),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('mision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.mision')),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
                ('resultado_esperado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.resultadoesperado')),
                ('vision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.vision')),
            ],
        ),
        migrations.AddField(
            model_name='estrategia',
            name='mision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.mision'),
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.estrategia')),
                ('medio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMM.medio')),
            ],
        ),
    ]
