# Generated by Django 4.2.1 on 2023-06-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('valor_total', models.FloatField(null=True)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=12, null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=10, null=True)),
                ('salario', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('marca', models.CharField(max_length=30, null=True)),
                ('valor', models.FloatField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.maquina')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('fecha', models.DateField(null=True)),
                ('resultados', models.TextField(null=True)),
                ('encargo', models.TextField(null=True)),
                ('encargos_resultados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.proveedores')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_Persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_cliente', to='ontologico.persona')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_medico', to='ontologico.persona')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_Optica',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores_Optica',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Compra',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.compra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Optica',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.rol'),
        ),
        migrations.CreateModel(
            name='Maquina_Persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.maquina')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.persona')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.persona'),
        ),
        migrations.CreateModel(
            name='Capacitacion_Persona',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.capacitacion')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ontologico.persona')),
            ],
        ),
    ]
