# Generated by Django 4.2.1 on 2023-06-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0001_initial'),
        ('portafolio_servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='descripcion',
            field=models.TextField(default='Descripción predeterminada'),
        ),
        migrations.AddField(
            model_name='actor',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='actor',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ServicioNegocio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portafolio_servicios.lineanegocio')),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portafolio_servicios.actor')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portafolio_servicios.servicionegocio')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoNegocio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portafolio_servicios.servicionegocio')),
            ],
        ),
    ]
