# Generated by Django 4.2.1 on 2023-06-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura_negocio.actividad')),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura_negocio.actividad')),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('optica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optica.opticasolygafas')),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura_negocio.componente')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura_negocio.canal'),
        ),
    ]
